version: '3.9'

services:
  pfs-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pfs_database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
